version: '3.4'
services:
  game_server:
    image: lugobots/server:${SERVER_VERSION:-latest}
    command: play --dev-mode --timer-mode=wait
    ports:
      - "5000:5000"
      - "8080:8080"
  player_01:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=1
      - BOT_TEAM=home
  player_02:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=2
      - BOT_TEAM=home
  player_03:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=3
      - BOT_TEAM=home
  player_04:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=4
      - BOT_TEAM=home
  player_05:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=5
      - BOT_TEAM=home
  player_06:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=6
      - BOT_TEAM=home
  player_07:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=7
      - BOT_TEAM=home
  player_08:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=8
      - BOT_TEAM=home
  player_09:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=9
      - BOT_TEAM=home
  player_10:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=10
      - BOT_TEAM=home
  player_11:
    image: ${MY_BOT}
    network_mode: "host"
    depends_on:
      - game_server
    environment:
      - BOT_NUMBER=11
      - BOT_TEAM=home
  player_away_01:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=1
      - BOT_TEAM=away
  player_away_02:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=2
      - BOT_TEAM=away
  player_away_03:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=3
      - BOT_TEAM=away
  player_away_04:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=4
      - BOT_TEAM=away
  player_away_05:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=5
      - BOT_TEAM=away
  player_away_06:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=6
      - BOT_TEAM=away
  player_away_07:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=7
      - BOT_TEAM=away
  player_away_08:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=8
      - BOT_TEAM=away
  player_away_09:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=9
      - BOT_TEAM=away
  player_away_10:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=10
      - BOT_TEAM=away
  player_away_11:
    image: ${AWAY_BOT:-lugobots/the-dummies-go:latest}
    network_mode: "host"
    environment:
      - BOT_NUMBER=11
      - BOT_TEAM=away



